// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTN.FRCU.ISI.TdP.AccountManager.DAL.EntityFramework;

namespace UTN.FRCU.ISI.TdP.AccountManager.Migrations
{
    [DbContext(typeof(AccountManagerDbContext))]
    [Migration("20211127160447_add-document-class")]
    partial class adddocumentclass
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UTN.FRCU.ISI.TdP.AccountManager.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("OverdraftLimit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("UTN.FRCU.ISI.TdP.AccountManager.Domain.AccountMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountMovements");
                });

            modelBuilder.Entity("UTN.FRCU.ISI.TdP.AccountManager.Domain.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentType", "DocumentNumber");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("UTN.FRCU.ISI.TdP.AccountManager.Domain.Document", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Number")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Type", "Number");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("UTN.FRCU.ISI.TdP.AccountManager.Domain.Account", b =>
                {
                    b.HasOne("UTN.FRCU.ISI.TdP.AccountManager.Domain.Client", "Client")
                        .WithMany("Accounts")
                        .HasForeignKey("ClientId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("UTN.FRCU.ISI.TdP.AccountManager.Domain.AccountMovement", b =>
                {
                    b.HasOne("UTN.FRCU.ISI.TdP.AccountManager.Domain.Account", null)
                        .WithMany("Movements")
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("UTN.FRCU.ISI.TdP.AccountManager.Domain.Client", b =>
                {
                    b.HasOne("UTN.FRCU.ISI.TdP.AccountManager.Domain.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentType", "DocumentNumber");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("UTN.FRCU.ISI.TdP.AccountManager.Domain.Account", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("UTN.FRCU.ISI.TdP.AccountManager.Domain.Client", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
